### ISSUE TITLE
Publish docker image in DockerHub

### ISSUE THREAD

**Issue by kaakaa** [amzn/oss-dashboard#110]
Would you like to register Docker image of `oss-dashboard` in [DockerHub](https://hub.docker.com/)?
If you publish docker image in DockerHub, it become more easy for everyone to use `oss-dashboard` without building docker image.

Building and publishing docker image in DockerHub can be done automatically. So you need only making account and setting a little at first.
[Configure automated builds on Docker Hub | Docker Documentation](https://docs.docker.com/docker-hub/builds/#remote-build-triggers)

I make sample image from my forked repository.
[kaakaa/oss-dashboard - Docker Hub](https://hub.docker.com/r/kaakaa/oss-dashboard/)

**Comment by hyandell** [comment]
Not currently. I'd want to look more at the postgres:alpine and ruby:2.2.6-slim to understand what they include before packaging up a docker image on DockerHub.

**Comment by jamesiri** [comment]
#142
