### ISSUE TITLE
Fetching collaborator stats breaks if org name != org login

### ISSUE THREAD

**Issue by MaineC** [amzn/oss-dashboard#111]
What I did:

* Set oss-dashboard to fetch private information with private-access: ['org-name'].
* Executed ruby refresh-dashboard.rb config_goes_here

What I expected:

At least the backing database to be filled with team membership and collaborator information.

What I got instead:

metadata
  org-name Error during processing: GET https://api.github.com/users/Org%20name/repos?per_page=100: 404 - Not Found // See: https://developer.github.com/v3/repos/#list-user-repositories
Backtrace:
	/usr/lib/ruby/vendor_ruby/octokit/response/raise_error.rb:16:in `on_complete'
	/usr/lib/ruby/vendor_ruby/faraday/response.rb:9:in `block in call'
	/usr/lib/ruby/vendor_ruby/faraday/response.rb:57:in `on_complete'
	/usr/lib/ruby/vendor_ruby/faraday/response.rb:8:in `call'
	/usr/lib/ruby/vendor_ruby/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	/usr/lib/ruby/vendor_ruby/octokit/middleware/follow_redirects.rb:61:in `call'
	/usr/lib/ruby/vendor_ruby/faraday/rack_builder.rb:139:in `build_response'
	/usr/lib/ruby/vendor_ruby/faraday/connection.rb:377:in `run_request'
	/usr/lib/ruby/vendor_ruby/faraday/connection.rb:140:in `get'
	/usr/lib/ruby/vendor_ruby/sawyer/agent.rb:94:in `call'
	/usr/lib/ruby/vendor_ruby/octokit/connection.rb:154:in `request'
	/usr/lib/ruby/vendor_ruby/octokit/connection.rb:84:in `paginate'
	/usr/lib/ruby/vendor_ruby/octokit/client/repositories.rb:71:in `repositories'
	/home/isabel/projects/oss/oss-dashboard/github-sync/db_metadata/sync-metadata.rb:121:in `store_organization_members'
	/home/isabel/projects/oss/oss-dashboard/github-sync/db_metadata/sync-metadata.rb:177:in `block (2 levels) in sync_metadata'
	/var/lib/gems/2.3.0/gems/sequel-4.46.0/lib/sequel/database/transactions.rb:224:in `_transaction'
	/var/lib/gems/2.3.0/gems/sequel-4.46.0/lib/sequel/database/transactions.rb:199:in `block in transaction'
	/var/lib/gems/2.3.0/gems/sequel-4.46.0/lib/sequel/database/connecting.rb:301:in `block in synchronize'
	/var/lib/gems/2.3.0/gems/sequel-4.46.0/lib/sequel/connection_pool/threaded.rb:107:in `hold'
	/var/lib/gems/2.3.0/gems/sequel-4.46.0/lib/sequel/database/connecting.rb:301:in `synchronize'
	/var/lib/gems/2.3.0/gems/sequel-4.46.0/lib/sequel/database/transactions.rb:165:in `transaction'
	/home/isabel/projects/oss/oss-dashboard/github-sync/db_metadata/sync-metadata.rb:170:in `block in sync_metadata'
	/home/isabel/projects/oss/oss-dashboard/github-sync/db_metadata/sync-metadata.rb:166:in `each'
	/home/isabel/projects/oss/oss-dashboard/github-sync/db_metadata/sync-metadata.rb:166:in `sync_metadata'
	/home/isabel/projects/oss/oss-dashboard/github-sync/sync.rb:52:in `github_sync'
	refresh-dashboard.rb:210:in `block in <main>'
	refresh-dashboard.rb:197:in `each'
	refresh-dashboard.rb:197:in `<main>'

**Comment by hyandell** [comment]
I applied your patch - thank you for providing it; definite error in the code :)
