### ISSUE TITLE
Latest licensee seems to cause issues

### ISSUE THREAD

**Issue by hyandell** [amzn/oss-dashboard#129]
I get:

in `raise_if_conflicts': Unable to activate licensee-9.9.2, because octokit-4.10.0 conflicts with octokit (~> 4.8.0) (Gem::ConflictError)

I'm not sure why 4.10.0 is clashing with > 4.8.0. 

Currently I fix it by locally making the Gemfile for licensee be 8.7 rather than ~>.

**Comment by jamesiri** [comment]
#142 https://github.com/amzn/oss-dashboard/issues/142
