### ISSUE TITLE
Install error - Ruby and Bundler in instructions are incompatible

### ISSUE THREAD

**Issue by JonathanParrilla** [amzn/oss-dashboard#132]
> ERROR:  Error installing bundler:
	bundler requires Ruby version >= 2.3.0.

^ I get that error whether I am installing from source, or even when trying to install through docker and/or docker-compose.

OS - Ubuntu 16.04
Docker version - 18.09.2
Docker-Compose version - 1.8.0

Docker error output:

>  ---> d4c45cc8b417
Step 3/10 : WORKDIR /oss-dashboard
 ---> Running in 5850887386f5
Removing intermediate container 5850887386f5
 ---> a911832dfe6f
Step 4/10 : COPY ./Gemfile /oss-dashboard/Gemfile
 ---> ba740b78d227
Step 5/10 : COPY ./Gemfile.lock /oss-dashboard/Gemfile.lock
 ---> dd28662eae84
Step 6/10 : COPY ./Rakefile /oss-dashboard/Rakefile
 ---> 752e0dc3699f
Step 7/10 : RUN gem install bundler   && bundle install --path vendor/bundle
 ---> Running in 5dac0e82aecd
ERROR:  Error installing bundler:
	bundler requires Ruby version >= 2.3.0.
ERROR: Service 'dashboard' failed to build: The command '/bin/sh -c gem install bundler   && bundle install --path vendor/bundle' returned a non-zero code: 1

I think the instructions on installation need to be updated to reflect how to get this working every time.

**Comment by hyandell** [comment]
Thanks Jonathan. I'll take a look tomorrow.

**Comment by bootstraponline** [comment]
I'm seeing the same issue. It'd be great to setup CI for the project to prevent regressions in the builds.

**Comment by hyandell** [comment]
I got the same. Trying to install bundler wants Ruby to be 2.3.0+.

I'll fix the Gemfile to specify 2.4.5 (latest version of 2.4.x, which is the latest version I see on Amazon Linux's yum repositories).

**Comment by hyandell** [comment]
Fixed in https://github.com/amzn/oss-dashboard/commit/9a4c748100f15b6d27cb56a6da6977c7ebbc5c01
