### ISSUE TITLE
Docker ruby versions

### ISSUE THREAD

**Issue by miguelgflores-fever** [amzn/oss-dashboard#134]
When using the docker installation, doing `docker build -t oss-dashboard .` we will get the error:

```
ERROR:  Error installing bundler:
	bundler requires Ruby version >= 2.3.0.
```

Using the last ruby docker image as base, we will get the error:

`Your Ruby version is 2.6.3, but your Gemfile specified 2.4.5`

Using `ruby:2.4.5` as base image, it won't be able to install `libxslt-ruby`

<details>
Fetching libxml-ruby 2.9.0
Installing libxml-ruby 2.9.0 with native extensions
Fetching libxslt-ruby 1.1.1
Installing libxslt-ruby 1.1.1 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/oss-dashboard/vendor/bundle/ruby/2.4.0/gems/libxslt-ruby-1.1.1/ext/libxslt
/usr/local/bin/ruby -I /usr/local/lib/ruby/site_ruby/2.4.0 -r
./siteconf20190608-17-7m1v9b.rb extconf.rb
checking for ruby/io.h... yes
checking for inflate() in -lz... yes
checking for iconv_open() in -liconv... no
checking for libiconv_open() in -liconv... no
checking for libiconv_open() in -llibiconv... no
checking for iconv_open() in -llibiconv... no
checking for iconv_open() in -lc... yes
checking for xmlXPtrNewRange() in -lxml2... yes
checking for libxml/xmlversion.h... no
checking for libxml/xmlversion.h in
/opt/include/libxml2,/usr/local/include/libxml2,/usr/include/libxml2... yes
checking for xsltApplyStylesheet() in -lxslt... yes
checking for xslt.h... no
checking for xslt.h in
/opt/include/libxslt,/usr/local/include/libxslt,/usr/include/libxslt... yes
checking for exsltRegisterAll() in -lexslt... yes
checking for exslt.h... no
checking for exslt.h in
/opt/include/libexslt,/usr/local/include/libexslt,/usr/include/libexslt... yes
checking for ruby_libxml.h in
/oss-dashboard/vendor/bundle/ruby/2.4.0/gems/libxml-ruby-2.9.0/ext/libxml... yes
checking for Init_libxml_ruby() in -lxml_ruby... no
checking for Init_libxml_ruby() in -l:libxml_ruby.so... no
checking for Init_libxml_ruby() in -llibxml_ruby-x86_64-linux... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/local/bin/$(RUBY_BASE_NAME)
	--with-iconv-dir
	--without-iconv-dir
	--with-iconv-include
	--without-iconv-include=${iconv-dir}/include
	--with-iconv-lib
	--without-iconv-lib=${iconv-dir}/lib
	--with-zlib-dir
	--without-zlib-dir
	--with-zlib-include
	--without-zlib-include=${zlib-dir}/include
	--with-zlib-lib
	--without-zlib-lib=${zlib-dir}/lib
	--with-xml2-dir
	--without-xml2-dir
	--with-xml2-include
	--without-xml2-include=${xml2-dir}/include
	--with-xml2-lib
	--without-xml2-lib=${xml2-dir}/lib
	--with-xslt-dir
	--without-xslt-dir
	--with-xslt-include
	--without-xslt-include=${xslt-dir}/include
	--with-xslt-lib
	--without-xslt-lib=${xslt-dir}/lib
	--with-exslt-dir
	--without-exslt-dir
	--with-exslt-include
	--without-exslt-include=${exslt-dir}/include
	--with-exslt-lib
	--without-exslt-lib=${exslt-dir}/lib
	--with-zlib
	--without-zlib
	--with-iconvlib
	--without-iconvlib
	--with-iconvlib
	--without-iconvlib
	--with-libiconvlib
	--without-libiconvlib
	--with-libiconvlib
	--without-libiconvlib
	--with-clib
	--without-clib
	--with-xml2lib
	--without-xml2lib
	--with-xsltlib
	--without-xsltlib
	--with-exsltlib
	--without-exsltlib
	--with-xml_rubylib
	--without-xml_rubylib
	--with-:libxml_ruby.solib
	--without-:libxml_ruby.solib
	--with-libxml_ruby-x86_64-linuxlib
	--without-libxml_ruby-x86_64-linuxlib
 extconf failure: %s
      Need libxml-ruby
      Please install libxml-ruby or specify the path to the gem via:
        --with-libxml-ruby=/path/to/libxml-ruby gem

To see why this extension failed to compile, please check the mkmf.log which can
be found here:

/oss-dashboard/vendor/bundle/ruby/2.4.0/extensions/x86_64-linux/2.4.0/libxslt-ruby-1.1.1/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in
/oss-dashboard/vendor/bundle/ruby/2.4.0/gems/libxslt-ruby-1.1.1 for inspection.
Results logged to
/oss-dashboard/vendor/bundle/ruby/2.4.0/extensions/x86_64-linux/2.4.0/libxslt-ruby-1.1.1/gem_make.out

An error occurred while installing libxslt-ruby (1.1.1), and Bundler cannot
continue.
Make sure that `gem install libxslt-ruby -v '1.1.1' --source
'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  libxslt-ruby
The command '/bin/sh -c gem install bundler   && bundle install --path vendor/bundle' returned a non-zero code: 5
</details>

**Comment by jamesiri** [comment]
I see this was resolved by the #135 PR so I will resolve this issue. Thank you again Miguel for not only pointing out the issue but also fixing it!
