### ISSUE TITLE
docker-compose up may have issues on Mac

### ISSUE THREAD

**Issue by adzuci** [amzn/oss-dashboard#136]
This may be a user error or related to #133, but when running `docker-compose up` on Mojave with Docker 18.09.7, I see:

```
 extconf failure: %s
      Need libxml-ruby
      Please install libxml-ruby or specify the path to the gem via:
        --with-libxml-ruby=/path/to/libxml-ruby gem

To see why this extension failed to compile, please check the mkmf.log which can
be found here:

/oss-dashboard/vendor/bundle/ruby/2.4.0/extensions/x86_64-linux/2.4.0/libxslt-ruby-1.1.1/mkmf.log

extconf failed, exit code 1
```

`docker run -it 311d032ec7cf "cat /oss-dashboard/vendor/bundle/ruby/2.4.0/extensions/x86_64-linux/2.4.0/libxslt-ruby-1.1.1/mkmf.log"` shows: 

```
"gcc -o conftest -I/usr/local/include/ruby-2.4.0/x86_64-linux -I/usr/local/include/ruby-2.4.0/ruby/backward -I/usr/local/include/ruby-2.4.0 -I. -I/usr/local/include -I/usr/include/libxml2 -I/usr/include/libxslt -I/usr/include/libexslt -I/oss-dashboard/vendor/bundle/ruby/2.4.0/gems/libxml-ruby-2.9.0/ext/libxml    -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wno-tautological-compare -Wno-parentheses-equality -Wno-constant-logical-operand -Wno-self-assign -Wunused-variable -Wimplicit-int -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wno-packed-bitfield-compat -Wsuggest-attribute=noreturn -Wsuggest-attribute=format -Wno-maybe-uninitialized  -fPIC conftest.c  -L. -L/usr/local/lib -Wl,-rpath,/usr/local/lib -L/usr/local/lib -Wl,-rpath,/usr/local/lib -L/oss-dashboard/vendor/bundle/ruby/2.4.0/gems/libxml-ruby-2.9.0/ext/libxml -Wl,-rpath,/oss-dashboard/vendor/bundle/ruby/2.4.0/gems/libxml-ruby-2.9.0/ext/libxml -L. -fstack-protector -rdynamic -Wl,-export-dynamic    -lexslt -lxslt -lxml2 -lc -lz  -Wl,-rpath,/usr/local/lib -L/usr/local/lib -lruby -llibxml_ruby-x86_64-linux -lexslt -lxslt -lxml2 -lc -lz  -Wl,-rpath,/usr/local/lib -L/usr/local/lib -lruby-static -lpthread -lgmp -ldl -lcrypt -lm   -lc"
/usr/bin/ld: cannot find -llibxml_ruby-x86_64-linux
collect2: error: ld returned 1 exit status
```

I can reproduce the error in by running the bundler command and started to try to build on top of ruby-2.4.4 (by modifying https://github.com/amzn/oss-dashboard/blob/master/Dockerfile) but hit a few Bundler 2 errors.

Any help is appreciated!

**Comment by jamesiri** [comment]
Hey and thanks for bringing this to light. Right now we don't have the time to invest in resolving this issue but if you can determine a fix and submit a PR I would happily review and accept the changes.

**Comment by 3cpt** [comment]
Did someone try some workaround or fix it? I tried to play with the container without success.

Edit: I'm on a Mac but I'm using the docker approach (build and compose).

**Comment by kaakaa** [comment]
With fixing gem versions and update ruby version, it seems to work fine. See details in https://github.com/kaakaa/oss-dashboard/commit/648c61e8614d03ca69332eb9f459a98acd2dc903

I supposed that there are some conflicts between ruby:2.4.5 image, `libxml-ruby (2.9.0)`, and `libxslt-ruby (1.1.1)`...
