### ISSUE TITLE
Get Started mode

### ISSUE THREAD

**Issue by hyandell** [amzn/oss-dashboard#24]
Add a get started script, or a flag to refresh_dashboard that takes an org and a directory rather than a config file. 
It begins by creating that directory, if needed, and generating a standard configuration file for it. A github file is also made and the user instructed to:

a) Updated the github config file with their personal access token.
b) Then run in the normal way.

Alternatively it could wait on user input like a wizard, though I would always leave the personal access token adding to the file to the user.

**Comment by jamesiri** [comment]
#142
