### ISSUE TITLE
Adjust theme to match the Org avatar

### ISSUE THREAD

**Issue by hyandell** [amzn/oss-dashboard#35]
Assuming only one org being shown, use the colours in the avatar to define the theme of the page and the colours in the charting.

This could include: "Make the colours in the charting depend on the bootstrap theme".

**Comment by hyandell** [comment]
Noting that there are existing JavaScript libraries for this:

http://jariz.github.io/vibrant.js/
http://lokeshdhakar.com/projects/color-thief/

**Comment by jamesiri** [comment]
#142
