### ISSUE TITLE
Dockerfile?

### ISSUE THREAD

**Issue by jbenet** [amzn/oss-dashboard#74]
Hey would be nice to have a dockerfile with all the deps. Whether or not people use docker itself, a dockerfile with versions pegged is pretty good way to ensure repeatable, reliable deployments.

**Comment by hyandell** [comment]
That would be cool Juan - contributions much welcome (ie: I need to play more with Docker as I've only barely touched on it in the past).

**Comment by hyandell** [comment]
Noting that Yusuke provided a patch adding a dockerfile in #104 and I just merged it :)
