### ISSUE TITLE
db-cli-reportrunner broken

### ISSUE THREAD

**Issue by hyandell** [amzn/oss-dashboard#75]
The CLI method for running db reports (useful for testing) is broken as it didn't change when the db-report API changed to include context.

It needs to build up a new context and pass that along, which might mean simplifying its command line args to have the overall conf file passed in and the report to run. That might mean duplicating some code from elsewhere, so refactoring could be useful (like a separate Context file).

**Comment by hyandell** [comment]
Noting that I've updated it so it doesn't break. ie) it passes an empty context right now. If the report depends on the context, it will then break.

**Comment by jamesiri** [comment]
#142
