### ISSUE TITLE
Improve commit data

### ISSUE THREAD

**Issue by hyandell** [amzn/oss-dashboard#96]
Currently oss-dashboard only pulls some of the relevant commit data.

* Would be good to also pull the author/committer GitHub logins when they exist.
* Good to also pull the email address of the Git author/committer.
* Would be nice to identify whether a commit is a merge from a pull request. Doesn't seem to be in the API though (outside of the message starting with "Merge pull request #x". Frustratingly the GitHub site appears to be able to connect these, presumably not via the message.

**Comment by hyandell** [comment]
First one is done now.

**Comment by jamesiri** [comment]
#142
